version: '3.8'
services:
  roach1:
    image: cockroachdb/cockroach:v22.2.8
    volumes:
      - ROACH1_DATA:/cockroach/cockroach-data
      - ./db-dev-init/:/docker-entrypoint-initdb.d
    ports:
      - 26257:26257
      - 8080:8080
    command:
      - start-single-node
      - --insecure

  donation-management:
    build:
      context: .
      dockerfile: compose.Dockerfile
      target: builder
    depends_on:
      - roach1
    volumes:
      - .:/home/pptruser/app
    ports:
      - '8300:8300'
    command:
      - "no-watch"
    environment:
      - NODE_ENV=compose
    cap_add:
      - "SYS_ADMIN" # Required for puppeteer

volumes:
  ROACH1_DATA:
