version: '3.8'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v21.2.10
    volumes:
      - COCKROACH_DATA:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8080:8080
    command:
      - start-single-node
      - --insecure

  cockroach-init:
    image: cockroachdb/cockroach:v21.2.10
    depends_on:
      - cockroachdb
    volumes:
      - ./db-dev-init:/db-init
    environment:
      - COCKROACH_HOST=cockroachdb
      - COCKROACH_PORT=26257
      - COCKROACH_USER=root
      - COCKROACH_INSECURE=true
    entrypoint: /db-init/init.sh

  donation-management:
    build: .
    depends_on:
      - cockroachdb
    volumes:
      - .:/app
    ports:
      - '8300:8300'
    command:
      - npm
      - run
      - dev
    environment:
      - ENCRYPTION_KEY=db5269ea782af1896a4d0b05f9ff7ab66143c7b9583aa0b7de725b8362c8cfcd
volumes:
  COCKROACH_DATA:
